### ISSUE TITLE
[Enhancement]: BepInEX Mono Support

### ISSUE THREAD

**Issue by BlueFalconHD** [blackjack4494/UnityExplorer#1]
### Describe the new feature or enhancement

I really need this please help!

**Comment by blackjack4494** [comment]
It's a trivial task. Currently busy so this might take a week or two.

**Comment by BlueFalconHD** [comment]
Ok :)

**Comment by blackjack4494** [comment]
> Ok :)

[UnityExplorer.BepInEx6.Mono.zip](https://github.com/blackjack4494/UnityExplorer/files/12173025/UnityExplorer.BepInEx6.Mono.zip)

Give this a try. It is untested since I do not have any Mono Game to test it myself. The only thing I changed here is 
`using BepInEx.Unity.Mono;` 
so that BIE6 should recognize it as a mod and using the latest bepinex libs (bleeding edge 671). Everything else is exactly the same.

**Comment by mosamadeeb** [comment]
Since no one confirmed yet, I can confirm the build works with latest BE (673)
